// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx2Z-Ce-KkZ2St5UHko9S3rQb814L2gnQ',
    appId: '1:642302049076:web:c2526ec34d432b45b44361',
    messagingSenderId: '642302049076',
    projectId: 'book-swap-5078b',
    authDomain: 'book-swap-5078b.firebaseapp.com',
    storageBucket: 'book-swap-5078b.firebasestorage.app',
    measurementId: 'G-8JWFPQT4M9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoOAsnOsYvu842KWBnSrxOm57qQF7YnRg',
    appId: '1:642302049076:android:6322385a61ff5010b44361',
    messagingSenderId: '642302049076',
    projectId: 'book-swap-5078b',
    storageBucket: 'book-swap-5078b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDivwhRLdWxV4foIu6XxWKXqDBq726X7K8',
    appId: '1:642302049076:ios:18eff5f6762d3a11b44361',
    messagingSenderId: '642302049076',
    projectId: 'book-swap-5078b',
    storageBucket: 'book-swap-5078b.firebasestorage.app',
    iosBundleId: 'com.example.bookswapApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDivwhRLdWxV4foIu6XxWKXqDBq726X7K8',
    appId: '1:642302049076:ios:18eff5f6762d3a11b44361',
    messagingSenderId: '642302049076',
    projectId: 'book-swap-5078b',
    storageBucket: 'book-swap-5078b.firebasestorage.app',
    iosBundleId: 'com.example.bookswapApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAx2Z-Ce-KkZ2St5UHko9S3rQb814L2gnQ',
    appId: '1:642302049076:web:1360b6db6828d462b44361',
    messagingSenderId: '642302049076',
    projectId: 'book-swap-5078b',
    authDomain: 'book-swap-5078b.firebaseapp.com',
    storageBucket: 'book-swap-5078b.firebasestorage.app',
    measurementId: 'G-K3C342Q7W1',
  );

}