// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB67dVhAHrmxKvx2ueNGKL9X3e_c6j2pKo',
    appId: '1:882532195243:web:06265bc1a7f4a31f2050ee',
    messagingSenderId: '882532195243',
    projectId: 'bookswap-app-31c5c',
    authDomain: 'bookswap-app-31c5c.firebaseapp.com',
    storageBucket: 'bookswap-app-31c5c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnAUll81YrzlX-nixlh8bnkVmM5Pprr94',
    appId: '1:882532195243:android:7c862b7bec2db8c22050ee',
    messagingSenderId: '882532195243',
    projectId: 'bookswap-app-31c5c',
    storageBucket: 'bookswap-app-31c5c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrnSixEp3-gU3hr0rmeLJFbgTnBwAcGCY',
    appId: '1:882532195243:ios:c1033deea33629542050ee',
    messagingSenderId: '882532195243',
    projectId: 'bookswap-app-31c5c',
    storageBucket: 'bookswap-app-31c5c.firebasestorage.app',
    iosBundleId: 'com.example.bookswapApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrnSixEp3-gU3hr0rmeLJFbgTnBwAcGCY',
    appId: '1:882532195243:ios:c1033deea33629542050ee',
    messagingSenderId: '882532195243',
    projectId: 'bookswap-app-31c5c',
    storageBucket: 'bookswap-app-31c5c.firebasestorage.app',
    iosBundleId: 'com.example.bookswapApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB67dVhAHrmxKvx2ueNGKL9X3e_c6j2pKo',
    appId: '1:882532195243:web:c09ce543762aef132050ee',
    messagingSenderId: '882532195243',
    projectId: 'bookswap-app-31c5c',
    authDomain: 'bookswap-app-31c5c.firebaseapp.com',
    storageBucket: 'bookswap-app-31c5c.firebasestorage.app',
  );

}